### ISSUE TITLE
Typo in bootstrap80.php 

### ISSUE THREAD

**Issue by githoober** [symfony/polyfill#331] opened 2021-01-25 19:17 UTC
See https://github.com/symfony/polyfill/commit/05bcec163ab3f5885a2109babcdd91562114c337#r46349286,

`$encoding ??= mb_internal_encoding();` is not a valid PHP construct.

**Comment by BackEndTea** [comment] 2021-01-25 20:07
Do you mean `??=`? That was introduced in php 7.4.

The following two statements work the same.
```php
$a = $a ?? $b;
$a ??= $b;
```

**Comment by nicolas-grekas** [comment] 2021-01-25 21:28
Duplicate of https://github.com/symfony/polyfill/issues/326, see there for more info.

**Closed by nicolas-grekas** 2021-01-25 21:28 UTC
