### ISSUE TITLE
"hex2bin()"-polyfill break tests from swiftmailer (php 5.3)

### ISSUE THREAD

**Issue by voku** [symfony/polyfill#46] opened 2016-03-22 21:51 UTC
In the test-class (https://github.com/voku/swiftmailer/blob/5.x/tests/unit/Swift/Transport/Esmtp/Auth/NTLMAuthenticatorTest.php) from swiftmailer, there is already a simple polyfill for php 5.3. But when I use the "symfony-polyfill"-package, some of this tests will break... Here the test results via Travis-CI: https://travis-ci.org/voku/swiftmailer/jobs/117393133

**Comment by stof** [comment] 2016-03-23 10:04
The logic in the polyfill is the same than in the Swiftmailer test, except for the additional validation rules missing in Swiftmailer. Are you sure that your test failure is not an actual bug in your code detected by the tests ?

**Comment by binwiederhier** [comment] 2016-03-27 00:37
This is a duplicate of https://github.com/symfony/polyfill/issues/47

**Comment by nicolas-grekas** [comment] 2016-03-29 11:18
Close in #49

**Closed by nicolas-grekas** 2016-03-29 11:18 UTC
