### ISSUE TITLE
Inconsistent function calls in test cases

### ISSUE THREAD

**Issue by zonuexe** [symfony/polyfill#472] opened 2024-03-31 02:13 UTC
It is inconsistent whether to call built-in functions or polyfill methods in test cases.

refs https://github.com/symfony/polyfill/pull/471/files#r1545524686

I'm also interested in improving these tests, but it looks like I won't be able to get started for a while.

**Comment by nicolas-grekas** [comment] 2024-06-20 08:35
Closing as duplicate of #425

**Closed as not planned by nicolas-grekas** 2024-06-20 08:35 UTC
